### ISSUE TITLE
Freecam breaks tracers and nametags

### ISSUE THREAD

**Issue by CrimsonMaelstrom** [GreenScripter/WurstFork#18]
Tracers and nametags are rendered from the bodies perspective

**Comment by CrimsonMaelstrom** [comment]
Here's an example
![image](https://user-images.githubusercontent.com/67611425/98930500-15366680-2520-11eb-95d0-6f89fb2c4757.png)

**Comment by GreenScripter** [comment]
Commit c2322659be0edf5a7659c99cd5398efa4fcd8119 resolves the tracer issue trivially, fixing the nametags (and particles) requires modifying minecraft code.

**Comment by CrimsonMaelstrom** [comment]
The nametag scale hack is built directly in to minecraft's code?  The major problem that I was referring to is how the scaling hack causes the names to appear massive when the hack is active and the freecam is closer to a player than the body.
