### ISSUE TITLE
Freecam fog correction

### ISSUE THREAD

**Issue by CrimsonMaelstrom** [GreenScripter/WurstFork#4]
When a player's body is in a location with fog that restricts vision substantially, that fog follows the camera everywhere and restricts vision regardless of the camera's location.  This overlay can be removed with another hack, but it would be convenient if it were applied based on the position of the camera rather than the player so the overlay fits correctly.

What freecam in an open space looks like when a players body is in lava:
![image](https://user-images.githubusercontent.com/67611425/98523342-26316e80-22b9-11eb-91dc-08ddbd45d3a0.png)

**Comment by GreenScripter** [comment]
Due to the already existing hack this is extremely easy to implement.
