### ISSUE TITLE
Disconnect freecam and body rotation

### ISSUE THREAD

**Issue by CrimsonMaelstrom** [GreenScripter/WurstFork#6]
The orientation of the camera in freecam should not affect the player body rotation, as it can cause issues and doesn't have any advantages as it is right now.  For example, killauralegit forces the freecam to look in the angle that the player has to look to hit an entity, and hunt does the same

**Comment by GreenScripter** [comment]
This issue causes hacks that change the player's direction to also affect freecam.

**Comment by CrimsonMaelstrom** [comment]
Excavator is unable to

**Comment by CrimsonMaelstrom** [comment]
Sorry about that

**Comment by GreenScripter** [comment]
I know how to disconnect the camera's rotation from the player, but I will have to find a way to use the cursor movement for change it for it to work.
