### ISSUE TITLE
Flight vertical velocity issue 

### ISSUE THREAD

**Issue by CrimsonMaelstrom** [GreenScripter/WurstFork#7]
When hovering in the air with fly, projectiles thrown by the player are thrown with increasingly greater negative vertical velocity, making bows and crossbows entirely useless after a few seconds.

**Comment by GreenScripter** [comment]
This appears to be that the server racks up falling speed despite the player not moving which causes the arrows to bend down. Because of this it can't be truly fixed but only hacked around. I'm adding a checkbox for it since it makes precise flight movement slightly more difficult.
