### ISSUE TITLE
Flight + Freecam interaction

### ISSUE THREAD

**Issue by CrimsonMaelstrom** [GreenScripter/WurstFork#8]
Up and down controls on freecam cause a flying player to go up or down as well.  Directional arrows do not have the same problem.  This should probably be recategorized as an incompatibility.

**Comment by CrimsonMaelstrom** [comment]
On further testing, jetpack has the same problem.

**Comment by GreenScripter** [comment]
Note that while this is now fixed, most servers will still kick you for flying excessively, thus using freecam while flying isn't the best idea.
